backend:
  name: git-gateway
  branch: master

media_folder: "images/uploads"

collections: 
  - name: "about"
    label: "About Me"
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Description", name: "description", widget: "markdown" }