backend:
  name: git-gateway
  branch: master

media_folder: "images/uploads"

collections: 
  - name: "about"
    label: "About Me"
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Description", name: "description", widget: "markdown" }
  # - name: "skills"
  #   label: "Skills"
  #     fields:
  #       - { label: "Title", name: "title", widget: "string" }
  #       - { label: "Subtitle", name: "subtitle", widget: "string" }
  #       - label: "Skills list"
  #         name: "skills list"
  #         widget: "list"
  #         summary: "{{fields.image}} {{fields.name}}"
  #         fields: 
  #           - { label: "Skill name", name: "name", widget: "string" }
  #           - { label: "Image", name: "image", widget: "image" }