backend:
  name: git-gateway
  branch: master

media_folder: "images/uploads"

collections:
  - label: "Sections"
    name: "sections"
    files:
      - label: "About Me"
        name: "about"
        file: "site/content/about.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Description, name: description, widget: markdown}
          - {label: Thumbnail, name: thumbnail, widget: image}
      - label: "Skills"
        name: "skills"
        file: "site/content/skills.yml"
        widget: "list"
        summary: "{{fields.name}} {{fields.thumbnail}}"
        fields:
          - label: Skill
            name: skill
            widget: object
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Thumbnail, name: thumbnail, widget: image}